version: '3.1'
services:
  php-fpm:
    build:  '${PATH_PHP:-/home/usuario01/r2-projetos}/r2-docker-compose-config/7.4/phpdocker/php-fpm'
    working_dir: /app
    container_name: php7.4-lara-boleto
    volumes:
      - '.:/app'
      - '${PATH_PHP:-/home/usuario01/r2-projetos}/r2-docker-compose-config/7.4/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
    networks:
      - app-networks-r2

networks:
  app-networks-r2:
    driver: bridge
