version: '3.1'
services:
  webserver:
    image: 'nginx:alpine'
    container_name: lara-boleto
    working_dir: /app
    volumes:
      - '.:/app'
      - '/home/usuario01/r2-projetos/php/7.4/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '${APP_PORT:-80}:80'
    networks:
      - app-networks-r2
  php-fpm:
    build: /home/usuario01/r2-projetos/php/7.4/phpdocker/php-fpm
    working_dir: /app
    container_name: php7.4-lara-boleto
    volumes:
      - '.:/app'
      - '/home/usuario01/r2-projetos/php/7.4/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    networks:
      - app-networks-r2
networks:
  app-networks-r2:
    driver: bridge
